### ISSUE TITLE
Directory in git is in Train_Case, while source refers to package in snake_case.

### ISSUE THREAD

**Issue by dfj-gh** [LB--/MCModify#6]
'LB_Stuff' is checked into git, while 'lb_stuff' is referenced as the package name within the code.
  While this can be worked around in several ways on each client, it would presumably be preferable to rename the directory within the github repo at some point. Main issue is that on checking out a fresh copy from github, it did not build. Renaming the directory locally, lets the project build for a new user, while fiddling the case sensitivity git setting for the local repo will prevent the name change from showing as a difference between the local and remote (github) repos for the user.
  (I expect this is caused by the author's repo defaulting to ignore case differences between the current workspace and the local repo, while some other folks do not have this default - likely due to a difference in the defaults between windows and other versions of git.)
  Not a critical issue, clearly - but it's fun closing easy issues. :)

**Comment by dfj-gh** [comment]
Normally this would require a pair of renames of the folder in git - but github can supposedly do it one step via the web interface.

**Comment by LB--** [comment]
Gah, yeah git on windows is a pain. I will fix it - sorry!

**Comment by dfj-gh** [comment]
Damn - well done; I'm not used to github, so, that rename does _not_ have a web gui option, and I just spent over an hour trying to get it done easily on a fork - without success. ;p
   Now to try out the code; just doing a quick script to move chunks and regions without relighting, but also without leaving the chunks, entities, tile entities sprayed all around. I'm racing against a 10-hour MCEdit task to do the same thing since it has not 'don't relight' option.
  Thanks muchly.

**Comment by LB--** [comment]
The library is severely outdated, ~~you may want to have a look at [this fork](https://github.com/omalley/clotho)~~ until I can find time to update this guy.

EDIT: Didn't notice the fork was only for the map item code. You may need to just absorb some of the chunk and region code into your project for now so that you can ignore e.g. unknown entities.
